name          'takumin-wp_cli'
version       '0.1.0'
source        ''
author        'takumin'
license       'Apache 2.0'
summary       ''
description   ''
project_page  ''

dependency 'puppetlabs/stdlib'
